INSERT INTO public.students (full_name, preferred_email)
VALUES 
  ('Julia Husainzada', 'juliahusainzada@gmail.com'),
  ('Hodo Abdulkarim', 'hodkarim64@gmail.com'),
  ('Pouya Anvari', 'pouya.anvari1393@gmail.com'),
  ('Crystal Doan', 'crystal.l.doan@sjsu.edu'),
  ('Dhwanil Ranpura', 'dhwanil.ranpura@sjsu.edu'),
  ('Vera Faith Del Rio', 'verafaith.delrio@sjsu.edu'),
  ('Tehkum Sultanali', 'tehkhumhusein.sultanali@sjsu.edu'),
  ('Jupjeet Rai', 'jupjeet.rai@sjsu.edu '),
  ('Pranavi Kristipati', 'pranavi.kristipati@sjsu.edu'),
  ('Hrishikesh Giri', 'hrishikesh.giri@sjsu.edu'),
  ('Devarsh Shroff', 'devarsh.shroff@sjsu.edu'),
  ('Pearl Shah', 'pearl.shah@sjsu.edu'),
  ('Aysha Mujeeb', 'aysha.mujeeb@sjsu.edu'),
  ('Madiha Fatima', 'madihafatima@sjsu.edu'),
  ('Trisha Subramanian', 'trisha.subramanian@sjsu.edu'),
  ('Shareen Rodrigues', 'shareensaimon.rodrigues@sjsu.edu'),
  ('Eesha Maddali', 'eesha.maddali@sjsu.edu'),
  ('Preethi Mohan', 'preethi.mohan01@sjsu.edu'),
  ('Matthew Bernard', 'matthew.bernard@sjsu.edu'),
  ('Caleb Fringer', 'caleb.fringer@sjsu.edu'),
  ('Alison Lau', 'alison.lau@sjsu.edu'),
  ('Gianna Pauline Nicomedes', 'gianna.nicomedes@sjsu.edu'),
  ('John Gutierrez', 'carlos.will51@gmail.com'),
  ('Rithika Sridharbabu', 'rithika.sridharbabu@sjsu.edu'),
  ('Zara Rahim', 'zararahim1205@gmail.com'),
  ('Izabella Doser', 'izabella.doser@sjsu.edu'),
  ('Tabassum Zahir', 'tabassum.zahir@sjsu.edu'),
  ('Mariam Jamil', 'mariam.jamil@sjsu.edu'),
  ('Don Dang', 'dang.dang@sjsu.edu'),
  ('Samriddhi Matharu', 'samriddhimatharu1@gmail.com'),
  ('Sherine Aldrin', 'sherine.aldrin@gmail.com'),
  ('Surabhi Bage', 'surabhi.bage@sjsu.edu'),
  ('Sowmika Yeturu', 'sowmika374@gmail.com'),
  ('Tejesh Remuduru', 'tejesh.remuduru@gmail.com'),
  ('Nancy Kanda', 'nancyknd29@gmail.com'),
  ('Marc McDaniel', 'marc.mcdaniel@sjsu.edu'),
  ('Yug More', 'yugamol.more@sjsu.edu'),
  ('Asmita Dulla', 'asmita.dulla@sjsu.edu'),
  ('Zainab Shaikh', 'zainab.r.shaikh@sjsu.edu '),
  ('Vani Sethi', 'vani.v.sethi@gmail.com'),
  ('Keya Chaudhari', 'keyachaudhari022@gmail.com'),
  ('Om Shah', 'om.shah@sjsu.edu '),
  ('Saahi Madras Sivakumar', 'saahithya.sivakumar@gmail.com'),
  ('Bhoomika Gupta', 'bhoomika.gupta@sjsu.edu'),
  ('Jennifer Lucero', 'jennifer.lucero@sjsu.edu'),
  ('Alice Wu', 'alice.wu724@gmail.com'),
  ('Sai Akshaya Buddharaju', 'akshayabuddharaju@gmail.com'),
  ('Dhatrisri Tummala', 'dhatrisri.tummala@sjsu.edu'),
  ('Shanglong Chen', 'shanglongc79@gmail.com'),
  ('Chris Le', 'chris.le@sjsu.edu'),
  ('Madelyn Whitney', 'madelyn.whitney@sjsu.edu'),
  ('Vy "Evie" Ho', 'evie.ho@sjsu.edu'),
  ('Marisa Quinones', 'marisagquinones@gmail.com'),
  ('Selina Mei', 'selina.mei@sjsu.edu'),
  ('Geeta Renavikar', 'geeta.renavikar@sjsu.edu'),
  ('Harsha Ramesh', 'harsha.ramesh@sjsu.edu'),
  ('Yuwen Zhang', 'yuwen.zhang@sjsu.edu'),
  ('Sumaiyah Alamgir', 'sumaiyah.alamgir@sjsu.edu'),
  ('Yamini Karthik', 'yamini.karthik06@gmail.com'),
  ('Harshitha Venkateswaran', 'harshivenkat11@gmail.com'),
  ('Amishi Seth', 'amishi.seth@sjsu.edu'),
  ('Siddarth Shekhar', 'siddarth.shekhar@sjsu.edu'),
  ('Shubh Rawal', 'shubhster25@gmail.com'),
  ('Akash Karthik', 'akash.karthik@sjsu.edu'),
  ('Ashton Moraes', 'ashton.moraes@sjsu.edu'),
  ('Shravya Parampalli', 'shravya.parampalli@sjsu.edu'),
  ('Ashley Chen', 'ashley.chen01@sjsu.edu'),
  ('Phuong Hua', 'phuong.hua@sjsu.edu'),
  ('Bhavya Vatsavayi', 'bhavyapreethika.vatsavayi@sjsu.edu');

WITH staging_data (team, name, role, headshot_url) AS (
    VALUES
	('Executive Board','Julia Husainzada','President','julia-husainzada.jpg'),
	('Executive Board','Hodo Abdulkarim','External Vice President','hodo-abdulkarim.jpg'),
	('Executive Board','Emily Leson','Internal Vice President','emily-leson.jpeg'),
	('Executive Board','Melanie Regalado Hernandez','Publicity Vice President','melanie-regalado-hernandez.jpg'),
	('Executive Board','Anusha Damle','Treasurer','anusha-damle.jpg'),
	('Executive Board','Vera Faith Del Rio','Secretary','verafaith-delrio.jpg'),
	('Workshops','Jupjeet Rai','Lead Ambassador','jupjeet-rai.jpeg'),
	('Workshops','Pranavi Kristipati','Workshops Ambassador','pranavi-kristipati.jpg'),
	('Workshops','Hrishikesh Giri','Workshops Ambassador','hrishikesh-giri.jpg'),
	('Workshops','Devarsh Shroff','Workshops Ambassador','devarsh-shroff.jpg'),
	('Workshops','Pearl Shah','Workshops Ambassador','pearl-shah.jpg'),
	('Workshops','Aysha Mujeeb','Workshops Ambassador','aysha-mujeeb.jpg'),
	('Workshops','Madiha Fatima','Workshops Ambassador','madiha-fatima.jpg'),
	('Workshops','Annie Doan','Workshops Ambassador','annie-doan.jpg'),
	('Case','Geeta Renavikar','Lead Ambassador','geeta-renavikar.jpg'),
	('Case','Ashley Roman','Lead Ambassador','ashley-roman.jpeg'),
	('Case','Harsha Ramesh','Case Ambassador','harsha-ramesh.jpg'),
	('Case','Eesha Maddali','Case Ambassador','eesha-maddali.png'),
	('Case','Pranavi Kristipati','Case Ambassador','pranavi-kristipati.jpg'),
	('Consulting','Samriddhi Matharu','Lead Ambassador','samriddhi-matharu.jpg'),
	('Consulting','Surabhi Bage','Consulting Ambassador','surabhi-bage.jpg'),
	('Consulting','Lexine Asuncion','Consulting Ambassador','lexine-asuncion.jpg'),
	('Consulting','Sherine Aldrin','Consulting Ambassador','sherine-aldrin.jpg'),
	('Consulting','Aishwarya Anburaja','Consulting Ambassador','aishwarya-anburaja.jpg'),
	('Industry','Madison Ammirati','Lead Ambassador','madison-ammirati.jpg'),
	('Industry','Sejal Ghanate','Lead Ambassador','sejal-ghanate.jpg'),
	('Industry','Sumaiyah Alamgir','Industry Ambassador','sumaiyah-alamgir.png'),
	('Industry','Yamini Karthik','Industry Ambassador','yamini-karthik.jpeg'),
	('Industry','Yuwen Zhang','Industry Ambassador','yuwen-zhang.jpg'),
	('Industry','Harshitha Venkateswaran','Industry Ambassador','harshitha-venkateswaran.jpg'),
	('Industry','Diya Suresh','Industry Ambassador','diya-suresh.jpg'),
	('Web Development','Shareen Rodrigues','Lead Ambassador','shareen-rodrigues.jpg'),
	('Web Development','Eesha Maddali','Lead Ambassador','eesha-maddali.png'),
	('Web Development','Tyler Awender','Web Dev Ambassador','tyler-awender.png'),
	('Web Development','Connie Ly','Web Dev Ambassador','connie-ly.jpeg'),
	('Web Development','Preethi Mohan','Web Dev Ambassador','preethi-mohan.jpg'),
	('Web Development','Marl Jonson','Web Dev Ambassador','marl-jonson.jpg'),
	('Web Development','Matthew Bernard','Web Dev Ambassador','matthew-bernard.jpg'),
	('Web Development','Emily Thach','Web Dev Ambassador','emily-thach.jpg'),
	('Web Development','Caleb Fringer','Web Dev Ambassador','caleb-fringer.png'),
	('Web Development','Alvin Tran','Web Dev Ambassador','alvin-tran.jpg'),
	('Membership Outreach','Zara Rahim','Lead Ambassador','zara-rahim.jpg'),
	('Membership Outreach','Izabella Doser','Lead Ambassador','izabella-doser.jpg'),
	('Membership Outreach','Shravya Vinjamuri','Membership Outreach Ambassador','shravya-vinjamuri.jpeg'),
	('Membership Outreach','Updesh Sachdeva','Membership Outreach Ambassador','updesh-sachdeva.jpg'),
	('Membership Outreach','Tabassum Zahir','Membership Outreach Ambassador','tabassum-zahir.jpg'),
	('Membership Outreach','Mariam Jamil','Membership Outreach Ambassador','placeholder.png'),
	('Membership Outreach','Don Dang','Membership Outreach Ambassador','don-dang.jpg'),
	('Membership Outreach','Amishi Seth','Membership Outreach Ambassador','amishi-seth.jpg'),
	('Marketing','Melanie Regalado Hernandez','Lead Ambassador','melanie-regalado-hernandez.jpg'),
	('Marketing','Bhoomika Gupta','Lead Ambassador','bhoomika-gupta.jpg'),
	('Marketing','Jennifer Lucero','Digital Marketing Ambassador','jennifer-lucero.jpg'),
	('Marketing','Zara Raza','Digital Marketing Ambassador','zara-raza.jpg'),
	('Marketing','Saahi Madras Sivakumar','Digital Marketing Ambassador','saahi-madras-sivakumar.jpeg'),
	('Marketing','Marc McDaniel','Digital Marketing Ambassador','marc-mcdaniel.jpg'),
	('Marketing','Alice Wu','Digital Marketing Ambassador','alice-wu.jpg'),
	('Marketing','Chris Le','Graphic Design Ambassador','chris-le.jpg'),
	('Marketing','Madelyn Whitney','Graphic Design Ambassador','madelyn-whitney.jpg'),
	('Marketing','Vy "Evie" Ho','Graphic Design Ambassador','vy-ho.jpg'),
	('Journalism','Jan Abigail Acosta','Journalism Ambassador','jan-abigail-acosta.jpg'),
	('Journalism','Harika Chandrasekhar','Journalism Ambassador','harika-chandrasekhar.jpg'),
	('Growth Analytics','Asmita Dulla','Lead Ambassador','asmita-dulla.jpg'),
	('Growth Analytics','Sonya Sorkin','Growth Analytics Ambassador','sonya-sorkin.jpeg'),
	('Growth Analytics','Zainab Shaikh','Growth Analytics Ambassador','zainab-shaikh.jpg'),
	('Growth Analytics','Vani Sethi','Growth Analytics Ambassador','vani-sethi.jpg'),
	('Finance','Anusha Damle','Lead Ambassador','anusha-damle.jpg'),
	('Finance','Dhwanil Ranpura','Finance Ambassador','dhwanil-ranpura.jpg')
)
INSERT INTO public.ambassadors (student, team, role, headshot_url)
SELECT 
    s.id AS student,
    t.id AS team,
    sd.role,
    sd.headshot_url
FROM staging_data sd
JOIN public.students s ON s.full_name = sd.name
JOIN public.teams t ON t.name = sd.team;
